spring:
  datasource:
    url: 'jdbc:mariadb://172.17.0.2:3306/loja'
    password: password
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
